spring:     #spring配置项
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:      #mybatis配置
  type-aliases-package: org.hf.boot.springboot.pojo.entity      #配置实体类别名包路径，配置这个配置项在mapper里面就不需要写全限定名了，只需要写对应实体类名即可
  mapper-locations: classpath:mapper/*.xml      #配置mapper映射文件路径地址，如果没有则不写该项配置
  configuration:      #配置mybati日志配置项
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #配置mybatis日志后台输出
mapper:     #通用mapper配置项
  identity: MYSQL     #取回主键的方式
  not-empty: false      #是否判断字符串类型!=''
  mappers: org.hf.application.mybatis.multiple.datasource.mapper.BaseMapper      #基础mapper接口路径,在这里继承通用Mapper<T>

server:     #服务配置项
  port: 8088      #tomcat配置：修改tomcat端口 默认端口是8080

logging:      #配置日志的记录级别
  level:      #日志等级配置项
    org.hf: info      #表示以org.hf开头的类的日志记录级别是debug
    org.springframework: error     #表示以org.springframework开头的类的日志记录级别是info
