package org.hf.application.custom.order.mapper;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.hf.application.custom.order.pojo.entity.Flashorder;

import java.util.List;

/**
 * <p> 抢购单数据查询接口 </p>
 * @author hufei
 * @date 2023/3/25 17:52
*/
public interface FlashorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    long countByExample(FlashorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    int deleteByExample(FlashorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    @Delete({
        "delete from flashorder",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    @Insert({
        "insert into flashorder (productid, userid)",
        "values (#{productid,jdbcType=INTEGER}, #{userid,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Flashorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    int insertSelective(Flashorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    List<Flashorder> selectByExample(FlashorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, productid, userid",
        "from flashorder",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultType(Flashorder.class)
    Flashorder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Flashorder record, @Param("example") FlashorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Flashorder record, @Param("example") FlashorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Flashorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flashorder
     *
     * @mbg.generated
     */
    @Update({
        "update flashorder",
        "set productid = #{productid,jdbcType=INTEGER},",
          "userid = #{userid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Flashorder record);
}